# Generated by Django 4.2.5 on 2023-09-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_chatconversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='gpt_response',
        ),
        migrations.RemoveField(
            model_name='chatconversation',
            name='user_input',
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='conversation_history',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
