# Generated by Django 4.2.5 on 2023-09-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_chatconversation_gpt_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='gpt_response',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='user_input',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='conversation_history',
            field=models.TextField(null=True),
        ),
    ]
