# Generated by Django 4.2.5 on 2023-09-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_chatconversation_gpt_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='conversation_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
